syntax = "proto2";

package caffe;

message BlobShape {
  repeated int64 dim = 1 [packed = true];
}

message BlobProto {
  optional BlobShape shape = 7;
  repeated float data = 5 [packed = true];
  repeated float diff = 6 [packed = true];
  repeated double double_data = 8 [packed = true];
  repeated double double_diff = 9 [packed = true];

  optional int32 num = 1 [default = 0];
  optional int32 channels = 2 [default = 0];
  optional int32 height = 3 [default = 0];
  optional int32 width = 4 [default = 0];
}

message BlobProtoVector {
  repeated BlobProto blobs = 1;
}

message FillerParameter {
  optional string type = 1 [default = 'constant'];
  optional float value = 2 [default = 0];
  optional float min = 3 [default = 0];
  optional float max = 4 [default = 1];
  optional float mean = 5 [default = 0];
  optional float std = 6 [default = 1];
  optional int32 sparse = 7 [default = -1];
  enum VarianceNorm {
    FAN_IN = 0;
    FAN_OUT = 1;
    AVERAGE = 2;
  }
  optional VarianceNorm variance_norm = 8 [default = FAN_IN];
}

message NetParameter {
  optional string name = 1;
  repeated string input = 3;
  repeated BlobShape input_shape = 8;
  repeated int32 input_dim = 4;
  optional bool force_backward = 5 [default = false];
  optional NetState state = 6;
  optional bool debug_info = 7 [default = false];
  repeated LayerParameter layer = 100;
}

enum Phase {
   TRAIN = 0;
   TEST = 1;
}

message NetState {
  optional Phase phase = 1 [default = TEST];
  optional int32 level = 2 [default = 0];
  repeated string stage = 3;
}

message NetStateRule {
  optional Phase phase = 1;
  optional int32 min_level = 2;
  optional int32 max_level = 3;
  repeated string stage = 4;
  repeated string not_stage = 5;
}

message ParamSpec {
  optional string name = 1;
  optional DimCheckMode share_mode = 2;
  enum DimCheckMode {
    STRICT = 0;
    PERMISSIVE = 1;
  }
  optional float lr_mult = 3 [default = 1.0];
  optional float decay_mult = 4 [default = 1.0];
}

message LayerParameter {
  optional string name = 1;
  optional string type = 2;
  repeated string bottom = 3;
  repeated string top = 4;
  optional Phase phase = 10;
  repeated float loss_weight = 5;
  repeated ParamSpec param = 6;
  repeated BlobProto blobs = 7;
  repeated bool propagate_down = 11;
  repeated NetStateRule include = 8;
  repeated NetStateRule exclude = 9;

  optional InputParameter input_param = 143;
  optional ReLUParameter relu_param = 123;
  optional InnerProductParameter inner_product_param = 117;
  optional SoftmaxParameter softmax_param = 125;
  optional FlattenParameter flatten_param = 135;
  optional ConvolutionParameter convolution_param = 106;
  optional PoolingParameter pooling_param = 121;
  optional BatchNormParameter batch_norm_param = 139;
  optional ScaleParameter scale_param = 142;
  optional BiasParameter bias_param = 141;
  optional LossParameter loss_param = 140;
  optional AccuracyParameter accuracy_param = 144;
  optional SigmoidParameter sigmoid_param = 145;
  optional TanHParameter tanh_param = 146;
  optional PReLUParameter prelu_param = 147;
  optional ELUParameter elu_param = 148;
  optional DropoutParameter dropout_param = 149;
  optional ConcatParameter concat_param = 150;
  optional EltwiseParameter eltwise_param = 151;
  optional ReshapeParameter reshape_param = 152;
}

message SigmoidParameter {
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
  }
  optional Engine engine = 1 [default = DEFAULT];
}

message TanHParameter {
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
  }
  optional Engine engine = 1 [default = DEFAULT];
}

message PReLUParameter {
  optional FillerParameter filler = 1;
  optional bool channel_shared = 2 [default = false];
}

message ELUParameter {
  optional float alpha = 1 [default = 1];
}

message DropoutParameter {
  optional float dropout_ratio = 1 [default = 0.5];
}

message ConcatParameter {
  optional uint32 concat_dim = 1 [default = 1];
  optional int32 axis = 2 [default = 1];
}

message EltwiseParameter {
  enum EltwiseOp {
    PROD = 0;
    SUM = 1;
    MAX = 2;
  }
  optional EltwiseOp operation = 1 [default = SUM];
  repeated float coeff = 2;
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
  }
  optional Engine engine = 3 [default = DEFAULT];
}

message ReshapeParameter {
  optional BlobShape shape = 1;
  optional int32 axis = 2 [default = 0];
  optional int32 num_axes = 3 [default = -1];
}

message InputParameter {
  repeated BlobShape shape = 1;
}

message ReLUParameter {
  optional float negative_slope = 1 [default = 0];
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
  }
  optional Engine engine = 2 [default = DEFAULT];
}

message InnerProductParameter {
  optional uint32 num_output = 1;
  optional bool bias_term = 2 [default = true];
  optional FillerParameter weight_filler = 3;
  optional FillerParameter bias_filler = 4;
  optional int32 axis = 5 [default = 1];
  optional bool transpose = 6 [default = false];
}

message SoftmaxParameter {
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
  }
  optional Engine engine = 1 [default = DEFAULT];
  optional int32 axis = 2 [default = 1];
}

message FlattenParameter {
  optional int32 axis = 1 [default = 1];
  optional int32 end_axis = 2 [default = -1];
}

message ConvolutionParameter {
  optional uint32 num_output = 1;
  optional bool bias_term = 2 [default = true];
  repeated uint32 pad = 3;
  optional uint32 pad_h = 9 [default = 0];
  optional uint32 pad_w = 10 [default = 0];
  repeated uint32 kernel_size = 4;
  optional uint32 kernel_h = 11;
  optional uint32 kernel_w = 12;
  repeated uint32 stride = 5;
  optional uint32 stride_h = 13;
  optional uint32 stride_w = 14;
  repeated uint32 dilation = 18;
  optional uint32 dilation_h = 19;
  optional uint32 dilation_w = 20;
  optional uint32 group = 6 [default = 1];
  optional FillerParameter weight_filler = 7;
  optional FillerParameter bias_filler = 8;
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
  }
  optional Engine engine = 15 [default = DEFAULT];
  optional int32 axis = 16 [default = 1];
  optional bool force_nd_im2col = 17 [default = false];
}

message PoolingParameter {
  enum PoolMethod {
    MAX = 0;
    AVE = 1;
    STOCHASTIC = 2;
  }
  optional PoolMethod pool = 1 [default = MAX];
  optional uint32 pad = 3 [default = 0];
  optional uint32 pad_h = 9 [default = 0];
  optional uint32 pad_w = 10 [default = 0];
  optional uint32 kernel_size = 2;
  optional uint32 kernel_h = 11;
  optional uint32 kernel_w = 12;
  optional uint32 stride = 4 [default = 1];
  optional uint32 stride_h = 13;
  optional uint32 stride_w = 14;
  optional bool global_pooling = 15 [default = false];
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
  }
  optional Engine engine = 5 [default = DEFAULT];
  enum RoundMode {
    CEIL = 0;
    FLOOR = 1;
  }
  optional RoundMode round_mode = 16 [default = CEIL];
}

message BatchNormParameter {
  optional bool use_global_stats = 1;
  optional float moving_average_fraction = 2 [default = .999];
  optional float eps = 3 [default = 1e-5];
}

message ScaleParameter {
  optional int32 axis = 1 [default = 1];
  optional int32 num_axes = 2 [default = 1];
  optional bool bias_term = 3 [default = false];
  optional FillerParameter filler = 4;
  optional FillerParameter bias_filler = 5;
}

message BiasParameter {
  optional int32 axis = 1 [default = 1];
  optional int32 num_axes = 2 [default = 1];
  optional FillerParameter filler = 3;
}

message LossParameter {
  optional int32 ignore_label = 1;
  enum NormalizationMode {
    FULL = 0;
    VALID = 1;
    BATCH_SIZE = 2;
    NONE = 3;
  }
  optional NormalizationMode normalization = 3 [default = VALID];
  optional bool normalize = 2;
}

message AccuracyParameter {
  optional uint32 top_k = 1 [default = 1];
  optional int32 axis = 2 [default = 1];
  optional int32 ignore_label = 3;
}
