# Options.cmake - 构建选项与全局编译设置
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

option(CAFFE_CPU_ONLY "Build Caffe-FFI with CPU only support" ON)
option(CAFFE_FFI_ENABLE_DEBUG_LOG "Enable detailed debug logging for memory/container operations" ON)
option(CAFFE_FFI_ENABLE_BACKTRACE "Enable stack backtrace support for memory leak diagnosis" ON)
option(CAFFE_FFI_BUILD_TESTS "Build C++ unit tests" ON)
option(CAFFE_USE_BLAS "Use BLAS (OpenBLAS/MKL/cblas) for GEMM/GEMV acceleration. Set to OFF to force pure C++ fallback." ON)
option(CAFFE_FFI_ENABLE_COW "Enable Copy-on-Write optimization for N>=2 Split layers (Phase 2)" ON)
option(CAFFE_FFI_ENABLE_COW_PHASE3 "Enable Phase 3 large-N COW optimizations (batch refcount, lazy reshape)" OFF)

if(POLICY CMP0144)
  cmake_policy(SET CMP0144 NEW)
endif()
if(POLICY CMP0167)
  cmake_policy(SET CMP0167 NEW)
endif()
