[build-system]
requires = ["scikit-build-core>=0.10", "ninja>=1.11"]
build-backend = "scikit_build_core.build"

[project]
name = "xuan-core"
version = "0.1.0"
description = "Xuanspace 核心工具库"
requires-python = ">=3.14.6"
dependencies = []
authors = [
    {name = "xinetzone"}
]
license = {text = "MIT"}

[tool.scikit-build]
minimum-version = "0.10"
cmake.build-type = "Release"
wheel.packages = ["src/xuan_core"]
ninja.make-fallback = false
build.verbose = true