# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vta_config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'vta_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vta_config.proto\x12\x0bnpu_ffi.vta\"\xf4\x02\n\tVTAConfig\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x12\n\nhw_version\x18\x02 \x01(\t\x12\x15\n\rlog_bus_width\x18\n \x01(\r\x12\x15\n\rlog_inp_width\x18\x0b \x01(\r\x12\x15\n\rlog_wgt_width\x18\x0c \x01(\r\x12\x15\n\rlog_acc_width\x18\r \x01(\r\x12\x15\n\rlog_out_width\x18\x0e \x01(\r\x12\x11\n\tlog_batch\x18\x14 \x01(\r\x12\x14\n\x0clog_block_in\x18\x15 \x01(\r\x12\x15\n\rlog_block_out\x18\x16 \x01(\r\x12\x19\n\x11log_uop_buff_size\x18\x1e \x01(\r\x12\x19\n\x11log_inp_buff_size\x18\x1f \x01(\r\x12\x19\n\x11log_wgt_buff_size\x18  \x01(\r\x12\x19\n\x11log_acc_buff_size\x18! \x01(\r\x12\x11\n\tins_width\x18( \x01(\r\x12\x11\n\tuop_width\x18) \x01(\r\"\x85\x01\n\x0e\x44\x65\x66\x61ultConfigs\x12#\n\x03vta\x18\x01 \x01(\x0b\x32\x16.npu_ffi.vta.VTAConfig\x12&\n\x06vta_v3\x18\x02 \x01(\x0b\x32\x16.npu_ffi.vta.VTAConfig\x12&\n\x06vta_v4\x18\x03 \x01(\x0b\x32\x16.npu_ffi.vta.VTAConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vta_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VTACONFIG']._serialized_start=34
  _globals['_VTACONFIG']._serialized_end=406
  _globals['_DEFAULTCONFIGS']._serialized_start=409
  _globals['_DEFAULTCONFIGS']._serialized_end=542
# @@protoc_insertion_point(module_scope)
